In [5]:
import pandas as pd
df = pd.read_json("movies.json")
df

,title,year,cast,genres
0,After Dark in Central Park,1900,[],[]
1,Boarding School Girls' Pajama Parade,1900,[],[]
2,Buffalo Bill's Wild West Parad,1900,[],[]
3,Caught,1900,[],[]
4,Clowns Spinning Hats,1900,[],[]
...,...,...,...,...
28790,Bumblebee,2018,"[Hailee Steinfeld, John Cena, Jorge Lendeborg ...","[Action, Adventure, Science Fiction]"
28791,Welcome to Marwen,2018,"[Steve Carell, Leslie Mann, Diane Kruger, Falk...","[Fantasy, Drama]"
28792,Holmes and Watson,2018,"[Will Ferrell, John C. Reilly, Rebecca Hall, R...","[Action, Mystery, Comedy]"
28793,On the Basis of Sex,2018,"[Felicity Jones, Armie Hammer, Justin Theroux,...","[Biography, Drama]"
28794,Destroyer,2018,"[Nicole Kidman, Tatiana Maslany, Sebastian Sta...","[Crime, Thriller]"

In [6]:
df.shape

(28795, 4)

In [7]:
df.head()

                                  title  year cast genres
0            After Dark in Central Park  1900   []     []
1  Boarding School Girls' Pajama Parade  1900   []     []
2        Buffalo Bill's Wild West Parad  1900   []     []
3                                Caught  1900   []     []
4                  Clowns Spinning Hats  1900   []     []

In [8]:
df.tail()

,title,year,cast,genres
28790,Bumblebee,2018,"[Hailee Steinfeld, John Cena, Jorge Lendeborg ...","[Action, Adventure, Science Fiction]"
28791,Welcome to Marwen,2018,"[Steve Carell, Leslie Mann, Diane Kruger, Falk...","[Fantasy, Drama]"
28792,Holmes and Watson,2018,"[Will Ferrell, John C. Reilly, Rebecca Hall, R...","[Action, Mystery, Comedy]"
28793,On the Basis of Sex,2018,"[Felicity Jones, Armie Hammer, Justin Theroux,...","[Biography, Drama]"
28794,Destroyer,2018,"[Nicole Kidman, Tatiana Maslany, Sebastian Sta...","[Crime, Thriller]"

In [11]:
df.tail(50)

,title,year,cast,genres
28745,Goosebumps 2: Haunted Halloween,2018,"[Wendi McLendon-Covey, Madison Iseman, Jeremy ...","[Horror, Comedy]"
28746,Beautiful Boy,2018,"[Steve Carell, Timothée Chalamet, Maura Tierne...","[Biography, Drama]"
28747,The Oath,2018,"[Ike Barinholtz, Tiffany Haddish, John Cho, Ca...",[Comedy]
28748,Halloween,2018,"[Jamie Lee Curtis, Judy Greer, Andi Matichak, ...",[Horror]
28749,Can You Ever Forgive Me?,2018,"[Melissa McCarthy, Richard E. Grant, Jane Curt...","[Biography, Drama, Comedy]"
28750,Serenity,2018,"[Matthew McConaughey, Anne Hathaway, Diane Lan...","[Noir, Thriller, Drama]"
28751,Mid90s,2018,"[Sunny Suljic, Lucas Hedges, Katherine Waterston]",[Drama]
28752,What They Had,2018,"[Hilary Swank, Michael Shannon, Robert Forster...",[Drama]
28753,Wildlife,2018,"[Carey Mulligan, Jake Gyllenhaal, Ed Oxenbould...",[Drama]
28754,Hunter Killer,2018,"[Gerard Butler, Gary Oldman, Common, Toby Step...","[Action, Thriller]"
28755,Suspiria,2018,"[Dakota Johnson, Tilda Swinton, Mia Goth, Lutz...",[Horror]
28756,Indivisible,2018,"[Justin Bruening, Sarah Drew, Jason George, Ti...",[Drama]
28757,The Nutcracker and the Four Realms,2018,"[Keira Knightley, Mackenzie Foy, Eugenio Derbe...",[Fantasy]
28758,Bohemian Rhapsody,2018,"[Rami Malek, Lucy Boynton, Gwilym Lee, Ben Har...","[Biography, Drama, Musical]"
28759,Nobody's Fool,2018,"[Tiffany Haddish, Tika Sumpter, Omari Hardwick...",[Comedy]
28760,Boy Erased,2018,"[Lucas Hedges, Joel Edgerton, Nicole Kidman, R...",[Drama]
28761,A Private War,2018,"[Rosamund Pike, Jamie Dornan, Stanley Tucci, T...","[Biography, Drama]"
28762,Bodied,2018,"[Calum Worthy, Jackie Long, Rory Uphold, Dumbf...","[Comedy, Drama]"
28763,The Front Runner,2018,"[Hugh Jackman, Vera Farmiga, J. K. Simmons, Al...","[Biography, Drama]"
28764,The Grinch,2018,"[Benedict Cumberbatch, Rashida Jones, Kenan Th...","[Animated, Family, Comedy]"
28765,The Girl in the Spider's Web,2018,"[Claire Foy, Sverrir Gudnason, Lakeith Stanfie...","[Crime, Thriller]"
28766,Overlord,2018,"[Jovan Adepo, Wyatt Russell, Jacob Anderson, D...","[Action, Horror, Thriller]"
28767,Conundrum: Secrets Among Friends,2018,"[Shaun Cairo (Screenplay), Jo Marie Payton, Ga...","[Drama, Thriller]"
28768,Fantastic Beasts: The Crimes of Grindelwald,2018,"[Eddie Redmayne, Katherine Waterston, Alison S...","[Fantasy, Drama]"
28769,Widows,2018,"[Viola Davis, Michelle Rodriguez, Elizabeth De...","[Action, Thriller]"
28770,Instant Family,2018,"[Mark Wahlberg, Rose Byrne, Isabela Moner, Tig...",[Comedy]
28771,Ralph Breaks the Internet,2018,"[John C. Reilly, Sarah Silverman, Jack McBraye...","[Animated, Fantasy, Adventure, Comedy]"
28772,Creed II,2018,"[Michael B. Jordan, Sylvester Stallone, Tessa ...","[Sports, Drama]"
28773,Robin Hood,2018,"[Taron Egerton, Jamie Foxx, Ben Mendelsohn, Ev...","[Action, Adventure]"
28774,Green Book,2018,"[Viggo Mortensen, Mahershala Ali, Linda Cardel...",[Drama]
28775,The Favourite,2018,"[Emma Stone, Rachel Weisz, Olivia Colman, Nich...","[Biography, Drama]"
28776,Anna and the Apocalypse,2018,"[Ella Hunt, Malcolm Cumming, Marli Siu, Sarah ...","[Horror, Musical, Comedy]"
28777,If Beale Street Could Talk,2018,"[Kiki Layne, Stephan James, Teyonah Parris, Re...","[Drama, Romance]"
28778,Mary Queen of Scots,2018,"[Saoirse Ronan, Margot Robbie, Jack Lowden, Ma...","[Historical, Drama]"
28779,Under the Silver Lake,2018,"[Andrew Garfield, Riley Keough, Topher Grace, ...","[Noir, Crime, Thriller]"
28780,The Silence,2018,"[Miranda Otto, Stanley Tucci, John Corbett]","[Drama, Thriller]"
28781,This One's for the Ladies,2018,"[C-Pudding, Poundcake, Tyga & Raw Dawg, Sweet ...",[Documentary]
28782,Ben Is Back,2018,"[Lucas Hedges, Julia Roberts, Kathryn Newton, ...",[Drama]
28783,Mortal Engines,2018,"[Hera Hilmar, Robert Sheehan, Hugo Weaving, Ji...","[Science Fiction, Action, Adventure]"
28784,Spider-Man: Into the Spider-Verse,2018,"[Shameik Moore, Hailee Steinfeld, Mahershala A...","[Animated, Superhero, Action, Comedy]"
28785,The Mule,2018,"[Clint Eastwood, Bradley Cooper, Laurence Fish...","[Drama, Crime, Biography]"
28786,Vice,2018,"[Christian Bale, Amy Adams, Steve Carell, Sam ...","[Biography, Drama]"
28787,Second Act,2018,"[Jennifer Lopez, Vanessa Hudgens, Leah Remini,...","[Romance, Comedy]"
28788,Mary Poppins Returns,2018,"[Emily Blunt, Lin-Manuel Miranda, Ben Whishaw,...","[Musical, Fantasy]"
28789,Aquaman,2018,"[Jason Momoa, Amber Heard, Willem Dafoe, Patri...","[Superhero, Action, Adventure]"
28790,Bumblebee,2018,"[Hailee Steinfeld, John Cena, Jorge Lendeborg ...","[Action, Adventure, Science Fiction]"
28791,Welcome to Marwen,2018,"[Steve Carell, Leslie Mann, Diane Kruger, Falk...","[Fantasy, Drama]"
28792,Holmes and Watson,2018,"[Will Ferrell, John C. Reilly, Rebecca Hall, R...","[Action, Mystery, Comedy]"
28793,On the Basis of Sex,2018,"[Felicity Jones, Armie Hammer, Justin Theroux,...","[Biography, Drama]"
28794,Destroyer,2018,"[Nicole Kidman, Tatiana Maslany, Sebastian Sta...","[Crime, Thriller]"