In [7]:
import pandas as pd
df = pd.read_csv("Students_exams.csv")
df.head()

   gender  math score  reading score  writing score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [10]:
gender	=df["gender"]
gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [14]:
Students =df[["gender","math score"]]
Students

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [17]:
rows = df[5:7]
rows

   gender  math score  reading score  writing score
5  female          71             83             78
6  female          88             95             92

In [18]:
result =df.loc[3]
result

gender           male
math score         47
reading score      57
writing score      44
Name: 3, dtype: object

In [19]:
result = df.loc[:, ['gender']]
result

     gender
0    female
1    female
2    female
3      male
4      male
..      ...
995  female
996    male
997  female
998  female
999  female

[1000 rows x 1 columns]

In [20]:
result = df.loc[10:20, ['gender', 'math score']]
result

    gender  math score
10    male          58
11    male          40
12  female          65
13    male          78
14  female          50
15  female          69
16    male          88
17  female          18
18    male          46
19  female          54
20    male          66